language: python
# if command bellow need to executed in sudo
# add this line.
sudo: required
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
services:
  - mongodb
install:
  - sudo apt-get install build-essential python3-dev python3-setuptools \
                     python3-numpy python3-scipy \
                     libatlas-dev libatlas3gf-base
  - pip install -r requirements.txt
script:
  - sleep 15
  - python manage.py insertArticles testData/Hate-1000-1001.json
  - python manage.py test
