language: python
# if command bellow need to executed in sudo
# add this line.
# sudo: required
python:
  - 3.5
  - 3.6
services:
  - mongodb
install:
  - pip install -r requirements.txt
script:
  - sleep 15
  - python manage.py PTT_KCM_API makemigrations
  - python manage.py PTT_KCM_API migrate
  - python manage.py insertArticles testData/Hate-1000-1001.json
  - python manage.py test
