# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IpTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('mostFreqCity', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PTT_KCM_API.IpTable'),
        ),
    ]
