# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_KCM_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='user',
        ),
        migrations.AddField(
            model_name='iptable',
            name='ipList',
            field=models.ManyToManyField(to='PTT_KCM_API.IP'),
        ),
    ]
