# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_KCM_API', '0002_auto_20161029_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='continentName',
            field=models.CharField(default='taiwan', max_length=15),
        ),
        migrations.AddField(
            model_name='ip',
            name='countryName',
            field=models.CharField(default='taiwan', max_length=20),
        ),
        migrations.AddField(
            model_name='ip',
            name='stateProv',
            field=models.CharField(default='taiwan', max_length=30),
        ),
        migrations.AlterField(
            model_name='ip',
            name='city',
            field=models.CharField(default='taiwan', max_length=30),
        ),
    ]
