# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTT_KCM_API', '0003_auto_20161102_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip2location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_from', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ip_to', models.DecimalField(decimal_places=0, max_digits=10)),
                ('country_code', models.CharField(max_length=2)),
                ('countryName', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='ip',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ip',
            name='continentName',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='ip',
            name='countryName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ip',
            name='stateProv',
            field=models.CharField(default='', max_length=30),
        ),
    ]
